[package]
name = "dm-common"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
axum = { workspace = true, features = ["json"] }
